// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhMd5J8B9y92iKMulG_mSedoRw7J8IY64',
    appId: '1:142035497527:web:b93b3f02d2c50d6a7f05b2',
    messagingSenderId: '142035497527',
    projectId: 'auth-app-28e5b',
    authDomain: 'auth-app-28e5b.firebaseapp.com',
    storageBucket: 'auth-app-28e5b.firebasestorage.app',
    measurementId: 'G-CNXXRH3WGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd1DiJaa8YnSLXBMWPvj_dQ_d-DxAxPJg',
    appId: '1:142035497527:android:42a90166cecc248d7f05b2',
    messagingSenderId: '142035497527',
    projectId: 'auth-app-28e5b',
    storageBucket: 'auth-app-28e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBckMUG9w0CW6sPunL1zKNYDnRamoMgTDk',
    appId: '1:142035497527:ios:99932913950449437f05b2',
    messagingSenderId: '142035497527',
    projectId: 'auth-app-28e5b',
    storageBucket: 'auth-app-28e5b.firebasestorage.app',
    iosClientId: '142035497527-ajprmv7hvven0cs7ro89qsc5n7qif1ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.whisprChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBckMUG9w0CW6sPunL1zKNYDnRamoMgTDk',
    appId: '1:142035497527:ios:99932913950449437f05b2',
    messagingSenderId: '142035497527',
    projectId: 'auth-app-28e5b',
    storageBucket: 'auth-app-28e5b.firebasestorage.app',
    iosClientId: '142035497527-ajprmv7hvven0cs7ro89qsc5n7qif1ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.whisprChatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhMd5J8B9y92iKMulG_mSedoRw7J8IY64',
    appId: '1:142035497527:web:1ce356930d8608a27f05b2',
    messagingSenderId: '142035497527',
    projectId: 'auth-app-28e5b',
    authDomain: 'auth-app-28e5b.firebaseapp.com',
    storageBucket: 'auth-app-28e5b.firebasestorage.app',
    measurementId: 'G-WF5N25H6S7',
  );
}
